version: '3'
services:
    db:
        image: mongo
        command: --bind_ip_all
        ports:
            - '27000:27017'
        env_file:
        - .db.env
    dbui:
        image: mongo-express
        restart: always
        ports:
            - 0:8081
        labels:
            - traefik.enable=true
            - traefik.http.routers.dbui.rule=Host(`0xdb.localhost`)
            - traefik.http.routers.dbui.entrypoints=web
            - traefik.http.services.dbui.loadbalancer.server.port=8081
        env_file:
            - .db.env
    api:
        build:
            context: ./packages/api
            dockerfile: Dockerfile.prod
        image: 0x/api:latest
        ports: 
            - 8080:80
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`zrx.localhost`) || HostRegexp(`{.*}.localhost`) || HostRegexp(`{.*}.local`)"
            - "traefik.http.routers.api.entrypoints=web"
    traefik:
        image: "traefik:v2.1"
        command:
            - --entrypoints.web.address=:80
            - --providers.docker=true
            - --api.insecure
            - --ping=true
            - --providers.docker.exposedbydefault=true
            - --entryPoints.ping.address=:8082
            - --ping.entryPoint=ping
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        